# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-03 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
