# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-03 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0002_expense_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='text',
            new_name='expense',
        ),
    ]
