# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-03 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0004_auto_20171203_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='where',
            new_name='location',
        ),
    ]
