# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0008_expense_expense_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spend.ExpenseList'),
        ),
    ]
